# Generated by Django 6.0 on 2025-12-30 15:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_url', models.URLField(max_length=2048)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('platform', models.CharField(choices=[('youtube', 'YouTube'), ('facebook', 'Facebook'), ('tiktok', 'TikTok'), ('instagram', 'Instagram'), ('twitter', 'Twitter/X'), ('vimeo', 'Vimeo'), ('dailymotion', 'Dailymotion'), ('reddit', 'Reddit'), ('twitch', 'Twitch'), ('other', 'Other')], default='other', max_length=50)),
                ('quality', models.CharField(default='best', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('file_path', models.CharField(blank=True, max_length=1024)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('thumbnail_url', models.URLField(blank=True, max_length=2048)),
                ('error_message', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Download History',
                'verbose_name_plural': 'Download Histories',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='downloader__status_226bcd_idx'), models.Index(fields=['platform'], name='downloader__platfor_f613f3_idx'), models.Index(fields=['created_at'], name='downloader__created_b2d958_idx')],
            },
        ),
    ]
